[package]
name = "app_bundle_creator"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "*"
colog = "*"
toml = "*"
serde = "*"
serde_derive = "*"
clap = { version = "*", features = ["derive"] }
